version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    container_name: textbin_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB:       textbin
      POSTGRES_USER:     textbin_user
      POSTGRES_PASSWORD: changeme
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

volumes:
  pg_data:
